### ISSUE TITLE
Project does not build with current master branch of Maven

### ISSUE THREAD

**Issue by DidierLoiseau** [mthmulders/maven4-examples#1]
I don’t know if this is expected. It works fine with Maven 4.0.0-beta-4, but with the current master branch (both with [this build](https://github.com/apache/maven/actions/runs/11218931504) and with one I built myself using mvn 4.0.0-beta-4), I get an error. Am I living too much on the edge? :smile:  
```
~/IdeaProjects/maven4-examples/maven-4 git:[main]
mvn -V verify
Apache Maven 4.0.0-beta-5-SNAPSHOT (954eae7b5662a0dee31362d6adc6c740dcdb77aa)
Maven home: /home/didier/.sdkman/candidates/maven/master
Java version: 17.0.11, vendor: Oracle Corporation, runtime: /home/didier/.sdkman/candidates/java/17.0.11-oracle
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "6.8.0-45-generic", arch: "amd64", family: "unix"
[INFO] Scanning for projects...
[ERROR] Some problems were encountered while processing the POMs
[ERROR] The build could not read 6 projects -> [Help 1]
[ERROR]   
[ERROR]   The project org.apache.maven.samples.reactor:module-a:1-SNAPSHOT (/home/didier/IdeaProjects/maven4-examples/maven-4/module-a/pom.xml) has 2 errors
[ERROR]     'dependencies.dependency.version' for org.apache.maven.samples.reactor:module-a:jar is missing. @ org.apache.maven.samples.reactor:module-b:[unknown-version], file:///home/didier/IdeaProjects/maven4-examples/maven-4/module-b/pom.xml, line 13, column 9
[ERROR]     'dependencies.dependency.version' for org.apache.maven.samples.reactor:module-b:jar is missing. @ org.apache.maven.samples.reactor:module-c-2:[unknown-version], file:///home/didier/IdeaProjects/maven4-examples/maven-4/module-c/module-c-2/pom.xml, line 13, column 9
[ERROR]   
[ERROR]   The project org.apache.maven.samples.reactor:module-b:1-SNAPSHOT (/home/didier/IdeaProjects/maven4-examples/maven-4/module-b/pom.xml) has 2 errors
[ERROR]     'dependencies.dependency.version' for org.apache.maven.samples.reactor:module-a:jar is missing. @ org.apache.maven.samples.reactor:module-b:[unknown-version], file:///home/didier/IdeaProjects/maven4-examples/maven-4/module-b/pom.xml, line 13, column 9
[ERROR]     'dependencies.dependency.version' for org.apache.maven.samples.reactor:module-b:jar is missing. @ org.apache.maven.samples.reactor:module-c-2:[unknown-version], file:///home/didier/IdeaProjects/maven4-examples/maven-4/module-c/module-c-2/pom.xml, line 13, column 9
[ERROR]   
[ERROR]   The project org.apache.maven.samples.reactor:module-c-1:1-SNAPSHOT (/home/didier/IdeaProjects/maven4-examples/maven-4/module-c/module-c-1/pom.xml) has 2 errors
[ERROR]     'dependencies.dependency.version' for org.apache.maven.samples.reactor:module-a:jar is missing. @ org.apache.maven.samples.reactor:module-b:[unknown-version], file:///home/didier/IdeaProjects/maven4-examples/maven-4/module-b/pom.xml, line 13, column 9
[ERROR]     'dependencies.dependency.version' for org.apache.maven.samples.reactor:module-b:jar is missing. @ org.apache.maven.samples.reactor:module-c-2:[unknown-version], file:///home/didier/IdeaProjects/maven4-examples/maven-4/module-c/module-c-2/pom.xml, line 13, column 9
[ERROR]   
[ERROR]   The project org.apache.maven.samples.reactor:module-c-2:1-SNAPSHOT (/home/didier/IdeaProjects/maven4-examples/maven-4/module-c/module-c-2/pom.xml) has 2 errors
[ERROR]     'dependencies.dependency.version' for org.apache.maven.samples.reactor:module-a:jar is missing. @ org.apache.maven.samples.reactor:module-b:[unknown-version], file:///home/didier/IdeaProjects/maven4-examples/maven-4/module-b/pom.xml, line 13, column 9
[ERROR]     'dependencies.dependency.version' for org.apache.maven.samples.reactor:module-b:jar is missing. @ org.apache.maven.samples.reactor:module-c-2:[unknown-version], file:///home/didier/IdeaProjects/maven4-examples/maven-4/module-c/module-c-2/pom.xml, line 13, column 9
[ERROR]   
[ERROR]   The project org.apache.maven.samples.reactor:module-c:1-SNAPSHOT (/home/didier/IdeaProjects/maven4-examples/maven-4/module-c/pom.xml) has 2 errors
[ERROR]     'dependencies.dependency.version' for org.apache.maven.samples.reactor:module-a:jar is missing. @ org.apache.maven.samples.reactor:module-b:[unknown-version], file:///home/didier/IdeaProjects/maven4-examples/maven-4/module-b/pom.xml, line 13, column 9
[ERROR]     'dependencies.dependency.version' for org.apache.maven.samples.reactor:module-b:jar is missing. @ org.apache.maven.samples.reactor:module-c-2:[unknown-version], file:///home/didier/IdeaProjects/maven4-examples/maven-4/module-c/module-c-2/pom.xml, line 13, column 9
[ERROR]   
[ERROR]   The project org.apache.maven.samples.reactor:parent:1-SNAPSHOT (/home/didier/IdeaProjects/maven4-examples/maven-4/pom.xml) has 2 errors
[ERROR]     'dependencies.dependency.version' for org.apache.maven.samples.reactor:module-a:jar is missing. @ org.apache.maven.samples.reactor:module-b:[unknown-version], file:///home/didier/IdeaProjects/maven4-examples/maven-4/module-b/pom.xml, line 13, column 9
[ERROR]     'dependencies.dependency.version' for org.apache.maven.samples.reactor:module-b:jar is missing. @ org.apache.maven.samples.reactor:module-c-2:[unknown-version], file:///home/didier/IdeaProjects/maven4-examples/maven-4/module-c/module-c-2/pom.xml, line 13, column 9
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the '-e' switch
[ERROR] Re-run Maven using the '-X' switch to enable verbose output
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```
These errors go away if I add `<modelVersion>4.1.0</modelVersion>` (as per [MNG-8190](https://issues.apache.org/jira/browse/MNG-8190)) in the 2 mentioned poms (it’s 6 times the same 2 files), but then I get a compilation error, the dependencies are not there (this is with `-X`):
```
…
[INFO] --- compiler:3.13.0:testCompile (default-testCompile) @ module-b ---
[DEBUG] Loading mojo org.apache.maven.plugins:maven-compiler-plugin:3.13.0:testCompile from plugin realm ClassRealm[plugin>org.apache.maven.plugins:maven-compiler-plugin:3.13.0, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5ffd2b27]
[DEBUG] Configuring mojo execution 'org.apache.maven.plugins:maven-compiler-plugin:3.13.0:testCompile:default-testCompile' with basic configurator -->
[DEBUG]   (f) annotationProcessorPathsUseDepMgmt = false
[DEBUG]   (f) basedir = /home/didier/IdeaProjects/maven4-examples/maven-4/module-b
[DEBUG]   (f) buildDirectory = /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target
[DEBUG]   (f) compileSourceRoots = [/home/didier/IdeaProjects/maven4-examples/maven-4/module-b/src/test/java]
[DEBUG]   (f) compilerId = javac
[DEBUG]   (f) createMissingPackageInfoClass = true
[DEBUG]   (f) debug = true
[DEBUG]   (f) debugFileName = javac-test
[DEBUG]   (f) enablePreview = false
[DEBUG]   (f) encoding = UTF-8
[DEBUG]   (f) failOnError = true
[DEBUG]   (f) failOnWarning = false
[DEBUG]   (f) fileExtensions = [jar, class]
[DEBUG]   (f) forceJavacCompilerUse = false
[DEBUG]   (f) forceLegacyJavacApi = false
[DEBUG]   (f) fork = false
[DEBUG]   (f) generatedTestSourcesDirectory = /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/generated-test-sources/test-annotations
[DEBUG]   (f) mojoExecution = org.apache.maven.plugins:maven-compiler-plugin:3.13.0:testCompile {execution: default-testCompile}
[DEBUG]   (f) optimize = false
[DEBUG]   (f) outputDirectory = /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/test-classes
[DEBUG]   (f) outputTimestamp = 2001-01-01T00:00:00Z
[DEBUG]   (f) parameters = false
[DEBUG]   (f) project = MavenProject: org.apache.maven.samples.reactor:module-b:1-SNAPSHOT @ /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/pom.xml
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@6e02721d
[DEBUG]   (f) showCompilationChanges = false
[DEBUG]   (f) showDeprecation = false
[DEBUG]   (f) showWarnings = true
[DEBUG]   (f) skipMultiThreadWarning = false
[DEBUG]   (f) source = 1.7
[DEBUG]   (f) staleMillis = 0
[DEBUG]   (s) target = 1.7
[DEBUG]   (f) testPath = [/home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/test-classes, /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/classes, /home/didier/IdeaProjects/maven4-examples/maven-4/module-a/target/module-a-1-SNAPSHOT.jar]
[DEBUG]   (f) useIncrementalCompilation = true
[DEBUG]   (f) useModulePath = true
[DEBUG]   (f) verbose = false
[DEBUG] -- end configuration --
[DEBUG] Using compiler 'javac'.
[DEBUG] Adding /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/generated-test-sources/test-annotations to test-compile source roots:
  /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/src/test/java
[DEBUG] New test-compile source roots:
  /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/src/test/java
  /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/generated-test-sources/test-annotations
[DEBUG] CompilerReuseStrategy: reuseCreated
[DEBUG] useIncrementalCompilation enabled
[INFO]  New dependency detected: /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/classes/org/apache/maven/samples/reactor/modb/CalcImpl.class
[INFO]  Stale source detected: /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/src/test/java/org/apache/maven/samples/reactor/modb/CalcImplTest.java
[INFO] Recompiling the module because of changed dependency.
[DEBUG] Classpath:
[DEBUG]  /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/test-classes
[DEBUG]  /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/classes
[DEBUG]  /home/didier/IdeaProjects/maven4-examples/maven-4/module-a/target/module-a-1-SNAPSHOT.jar
[DEBUG] Source roots:
[DEBUG]  /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/src/test/java
[DEBUG]  /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/generated-test-sources/test-annotations
[DEBUG] Command line options:
[DEBUG] -d /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/test-classes -classpath /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/test-classes:/home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/classes:/home/didier/IdeaProjects/maven4-examples/maven-4/module-a/target/module-a-1-SNAPSHOT.jar: -sourcepath /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/src/test/java:/home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/generated-test-sources/test-annotations: -s /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/generated-test-sources/test-annotations -g -target 1.7 -source 1.7 -encoding UTF-8 -XDuseUnsharedTable=true
[DEBUG] incrementalBuildHelper#beforeRebuildExecution
[INFO] Compiling 1 source file with javac [debug target 1.7] to target/test-classes
[DEBUG] incrementalBuildHelper#afterRebuildExecution
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] bootstrap class path not set in conjunction with -source 7
[WARNING] source value 7 is obsolete and will be removed in a future release
[WARNING] target value 7 is obsolete and will be removed in a future release
[WARNING] To suppress warnings about obsolete options, use -Xlint:-options.
[INFO] 4 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/src/test/java/org/apache/maven/samples/reactor/modb/CalcImplTest.java:[4,29] package org.junit.jupiter.api does not exist
[ERROR] /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/src/test/java/org/apache/maven/samples/reactor/modb/CalcImplTest.java:[6,35] package org.assertj.core.api does not exist
[ERROR] /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/src/test/java/org/apache/maven/samples/reactor/modb/CalcImplTest.java:[6,1] static import only from classes and interfaces
[ERROR] /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/src/test/java/org/apache/maven/samples/reactor/modb/CalcImplTest.java:[11,6] cannot find symbol
  symbol:   class Test
  location: class org.apache.maven.samples.reactor.modb.CalcImplTest
[ERROR] /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/src/test/java/org/apache/maven/samples/reactor/modb/CalcImplTest.java:[13,9] cannot find symbol
  symbol:   method assertThat(int)
  location: class org.apache.maven.samples.reactor.modb.CalcImplTest
[INFO] 5 errors 
[INFO] -------------------------------------------------------------
[INFO] --------------------------------------------------------------------------------------------------------------------------
[INFO] Reactor Summary for parent 1-SNAPSHOT:
[INFO] 
[INFO] parent ............................................................................................... SUCCESS [  0.019 s]
[INFO] module-a ............................................................................................. SUCCESS [  0.829 s]
[INFO] module-b ............................................................................................. FAILURE [  0.097 s]
[INFO] module-c ............................................................................................. SKIPPED
[INFO] module-c-1 ........................................................................................... SKIPPED
[INFO] module-c-2 ........................................................................................... SKIPPED
[INFO] --------------------------------------------------------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] --------------------------------------------------------------------------------------------------------------------------
[INFO] Total time:  1.131 s
[INFO] Finished at: 2024-10-07T23:34:10+02:00
[INFO] --------------------------------------------------------------------------------------------------------------------------
```
This error gets fixed if I specify the `<version>` for `module-a` in `module-b`’s pom, but it shouldn’t be required.

p.s. re: my questions at Devoxx today, the answer is [MNG-8252](https://issues.apache.org/jira/browse/MNG-8252), but it’s only on master currently :smirk: I can indeed use an empty `<parent/>` when using it :slightly_smiling_face: And it’s even possible to omit the `xmlns` declarations as well!

**Comment by mthmulders** [comment]
First of all, thank you @DidierLoiseau for reporting this issue. It gives us valuable feedback. @rfscholte, @khmarbaise and myself discussed this during a break at Devoxx and we all agreed this should work - as it did in Maven 4.0.0-beta-4.

I've run a `git bisect` using on this project with `mvn validate` as the verification. The outcome is that [2d224623a32770401e0a5a8aecf1333797f89b8e](https://github.com/apache/maven/commit/2d224623a32770401e0a5a8aecf1333797f89b8e) is the first bad commit.

While this isn't a solution yet, at least it gives us some clue where to start looking.

**Comment by mthmulders** [comment]
I have reported an issue in the Apache Software Foundation JIRA to follow-up: [MNG-8301](https://issues.apache.org/jira/browse/MNG-8301).

**Comment by DidierLoiseau** [comment]
Following apache/maven-integration-testing#386, I rechecked it here by changing the `xmlns`, and it also fixes the first issue.

It still does not fix the compilation error though.

**Comment by mthmulders** [comment]
@DidierLoiseau, I did not only fix the namespace but also the schemaLocation for that namespace; see #2.

The compilation error might be caused by the fact that [AssertJ requires Java 8](https://assertj.github.io/doc/#assertj-core-java-versions). Since we wanted to highlight that Maven 4 requiring Java 17 does not have any implications for the code you build with Maven, we sticked with Java 1.7. Dropping AssertJ as the assertion and using JUnit's `Assertions` class seems to resolve it; see #3.

**Comment by DidierLoiseau** [comment]
> Dropping AssertJ as the assertion and using JUnit's `Assertions` class seems to resolve it; see #3.

I was compiling with Java 17 so that I don’t have to setup the toolchains. However what really fixes the problem in #3 is the `<dependencyManagement>`. If you remove it and set the version explicitly on the `junit-jupiter-api` dependency in `module-b` (as before), the error comes back.

With the `-X` flag, you can see a difference in the `compiler:testCompile` classpath. With `<dependencyManagement>`:

```
[DEBUG]   (f) testPath = [/home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/test-classes, /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/classes, /home/didier/IdeaProjects/maven4-examples/maven-4/module-a/target/module-a-1-SNAPSHOT.jar, /home/didier/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.11.2/junit-jupiter-api-5.11.2.jar, /home/didier/.m2/repository/org/opentest4j/opentest4j/1.3.0/opentest4j-1.3.0.jar, /home/didier/.m2/repository/org/junit/platform/junit-platform-commons/1.11.2/junit-platform-commons-1.11.2.jar, /home/didier/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar]
```
without it but with the explicit version in `module-b`:
```
[DEBUG]   (f) testPath = [/home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/test-classes, /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/classes, /home/didier/IdeaProjects/maven4-examples/maven-4/module-a/target/module-a-1-SNAPSHOT.jar]
```
… basically all dependencies are missing except `module-a`.

The issue still gets fixed if you set the version on the `module-a` dependency.

**Comment by mthmulders** [comment]
> ```
> [DEBUG]   (f) testPath = [/home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/test-classes, /home/didier/IdeaProjects/maven4-examples/maven-4/module-b/target/classes, /home/didier/IdeaProjects/maven4-examples/maven-4/module-a/target/module-a-1-SNAPSHOT.jar]
> ```
> 
> … basically all dependencies are missing except `module-a`.
> 
> The issue still gets fixed if you set the version on the `module-a` dependency.

That's really strange! Without the `<dependencyManagement>` for JUnit Jupiter, there is still an explicit dependency on JUnit Jupiter API, it has a version number, so why is it not present on the classpath?

**Comment by DidierLoiseau** [comment]
> there is still an explicit dependency on JUnit Jupiter API, it has a version number, so why is it not present on the classpath?

Exactly! Do you also reproduce that issue?

**Comment by jjkester** [comment]
I have had a quick look, and the JUnit and AssertJ dependencies are not in the effecitve POM of module b.

Command used: `mvn -pl module-b help:effective-pom -Dverbose`

It looks like an issue with dependency resolution in Maven, which is strange since it is a direct dependency.

**Comment by mthmulders** [comment]
After several hours of troubleshooting, @jjkester and myself have reported [MNG-8331](https://issues.apache.org/jira/browse/MNG-8331).

**Comment by mthmulders** [comment]
@DidierLoiseau, this should be fixed in the upcoming Apache Maven 4.0.0-beta-5 release. Thanks again for reaching out after our Devoxx talk, because that's how all of this started.

I believe we have now addressed all the issues you found when checking out this project. That's why I will close this issue. In case you find new issues, don't hesitate to open a new one or get in touch in another way.
